# Generated by Django 2.2.12 on 2020-10-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpproxy', '0002_auto_20160121_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestparameter',
            name='type',
            field=models.CharField(choices=[('G', 'GET'), ('P', 'POST')], default='G', max_length=1),
        ),
    ]
