# Generated by Django 2.2.12 on 2021-02-01 13:27

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cartomancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='open_since',
            field=partial_date.fields.PartialDateField(blank=True),
        ),
    ]
