version: '3'
volumes:
  postgres:

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgis/postgis
    container_name: postgres-postgis
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./backups:/opt/backups
    networks:
      - postgres_conn
    ports:
      - '5432:5432'
    env_file: .env
    restart: on-failure
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    env_file: .env
    restart: on-failure
  imgproxy:
    image: darthsim/imgproxy
    container_name: imgproxy
    ports:
      - "8080:8080"
    env_file: .env
  splash:
    image: scrapinghub/splash
    container_name: splash
    ports:
      - "8050:8050"

networks:
  postgres_conn:
    driver: bridge
