# Generated by Django 3.1.8 on 2021-04-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('denizens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AlterModelManagers(
            name='team',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='created',
        ),
        migrations.RemoveField(
            model_name='team',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='team',
            name='creator_username',
        ),
        migrations.RemoveField(
            model_name='team',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner_username',
        ),
        migrations.RemoveField(
            model_name='team',
            name='page',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated',
        ),
        migrations.AddField(
            model_name='team',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
    ]
