# Generated by Django 2.2.12 on 2020-11-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppet_show', '0003_auto_20201127_0146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionLog',
        ),
    ]
