# Generated by Django 2.2.12 on 2020-07-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_hangar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnbdata',
            name='room_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
