# Generated by Django 2.2.12 on 2021-01-14 18:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_hangar', '0002_auto_20200702_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('guid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name of the Spider')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='API Response')),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Scrapy Stats')),
            ],
        ),
        migrations.RemoveField(
            model_name='airbnbimage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='airbnbimage',
            name='scrapedimage_ptr',
        ),
        migrations.DeleteModel(
            name='AirBnBData',
        ),
        migrations.DeleteModel(
            name='AirBnBImage',
        ),
    ]
