# Generated by Django 2.2.12 on 2020-11-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendenstreet', '0002_subscriptionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
